config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  constraints(SubdomainPresent) do
    root 'articles#index', as: :subdomain_root
    devise_for :users
    resources :users, only: :index
  end

  constraints(SubdomainBlank) do
    root 'welcome#index'
    resources :accounts, only: [:new, :create]
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  RESTRICTED_SUBDOMAINS = %w(www)

  belongs_to :owner, class_name: 'User'

  validates :owner, presence: true
  validates :subdomain, presence: true,
                        uniqueness: { case_sensitive: false },
                        format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters' },
                        exclusion: { in: ['www'], message: 'restricted' }

  accepts_nested_attributes_for :owner

  before_validation :downcase_subdomain

  private

    def downcase_subdomain
      self.subdomain = subdomain.downcase
    end

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def new
    @account = Account.new
    @account.build_owner
  end

  def create
    @account = Account.new(account_params)
    if @account.valid?
      Apartment::Tenant.create(@account.subdomain)
      Apartment::Tenant.switch!(@account.subdomain)
      @account.save
      redirect_to new_user_session_url(subdomain: @account.subdomain)
    else
      render action: 'new'      
    end
  end

  private

    def account_params
      params.require(:account).permit(:subdomain, owner_attributes: [:name, :email, :password, :password_confirmation])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :load_schema, :authenticate_user!

  private

    def load_schema
      Apartment::Tenant.switch!('public')

      return unless request.subdomain.present?

      if current_account
        Apartment::Tenant.switch!(request.subdomain)
      else
        redirect_to root_url(subdomain: false)
      end
    end

    def current_account
      @current_account ||= Account.find_by(subdomain: request.subdomain)
    end
    helper_method :current_account

    def after_sign_in_path_for(resource)
      articles_path
    end

    def after_sign_out_path_for(resource)
      new_user_session_path
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/new.html.erb
<h2>Create An Account</h2>

<%= form_for @account do |f| %>
  <%= f.fields_for :owner do |o| %>
    <div>
      <%= o.label :name, 'Name' %><br/>
      <%= o.text_field :name %>
    </div>

    <div>
      <%= o.label :email, 'Email' %><br/>
      <%= o.email_field :email %>
    </div>

    <div>
      <%= o.label :password, 'Password' %><br/>
      <%= o.password_field :password %>
    </div>

    <div>
      <%= o.label :password_confirmation, 'Confirm Password' %><br/>
      <%= o.password_field :password_confirmation %>
    </div>
  <% end %>

  <div>
    <%= f.label :subdomain %><br/>
    <%= f.text_field :subdomain %>
  </div>

  <br/>

  <%= f.button :submit %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title, 'Title:' %>
    <%= f.text_field :title %>
  </div>

  </br>
  
  <div>
    <%= f.label :content, 'Content:' %>
    <%= f.text_area :content %>
  </div>

  </br>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Article Details</h3>

<div>
  <strong>Title</strong>
  <span>@article.title</span>
</div>

<div>
  <strong>Content</strong>
  <span>@article.content</span>
</div>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultiTenantApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if user_signed_in? %>
    <nav>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
    </nav>
  <% end %>

  <%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, 'Name:' %><br/>
    <%= f.text_field :name %>
  </div>

  </br>

  <div>
    <%= f.label :email, 'Email:' %><br/>
    <%= f.email_field :email %>
  </div>

  <br/>

  <div>
    <%= f.label :password, 'Password:' %><br/>
    <%= f.password_field :password %>
  </div>

  <br/>

  <div>
    <%= f.label :password_confirmation, 'Password Confirmation:' %><br/>
    <%= f.password_field :password_confirmation %>
  </div>

  <br/>

  <div>
    <%= f.label :subdomain, 'Subdomain:' %><br/>
    <%= f.text_field :subdomain %>
  </div>

 </br>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
      <th>email</th>
      <th>subdomain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.subdomain %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h3>User Details</h3>
<div>
  <strong>name:</strong>
  <span><%= @user.name %></span>
</div>

<div>
  <strong>email:</strong>
  <span><%= @user.email %></span>
</div>

<div>
  <strong>subdomain:</strong>
  <span><%= @user.subdomain %></span>
</div>

<br>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h3>Welcome to the multi-tenancy app.</h3>

<%= link_to 'Create Account', new_account_path %>